server:
  port: 8081
spring:
  application:
    name: SharingNearbySpots
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.206.181.204:3306/SharingNearbySpots?useSSL=false&serverTimezone=UTC
    username: root
    password: 990214Yy!
  mail:
    host: smtp.yeah.net  # 发送邮件的服务器地址
    port: 465
    username: zuoyue_1@yeah.net # 登录邮箱的账号
    password: WNMBFBZFBNMSBKID  # 开启 IMAP/SMTP服务 获得的授权码,而不是邮箱的登录密码
    default-encoding: UTF-8
    # 协议
    protocol: smtp
    #    properties:
    #      "mail.transport.protocol": smtp
    #      "mail.smtp.auth": true
    #      "mail.smtp.starttls.enable": true
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true


  redis:
    host: 43.206.181.204
    port: 6379
    password: 990214
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: SharingNearbySpots.entity # 别名扫描包
logging:
  level:
    SharingNearbySpots: debug